// CARDS_DATA
// Card data — ALL_CARDS array and DISCIPLINES
// Synced from online/cards.js — source of truth
// All functions and variables remain global.

// ═══════ SHELVED IDS — excluded from random encounters ═══════
const SHELVED_IDS = new Set([
  // 204 Finn — UNSHELVED (active on dashboard, Forge ability)
  316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 328, /*329 Clink active*/ 330, 331, 332, 333, 334, 335, 337, // Penny-Fuego
  338, 339, 340, 341, /*342 Calvin active*/ 344, 346, 347, 348, 349, 350, 351, 353, 354, 355, 356, 357, 358, 359,  // Thistle-Volcanic Heart
  360, 361, 362, 363, 364, 366, 367, 368                                                               // The Shepherd-Dragonclaw
]);

// Get all non-shelved cards
function getActiveCards() { return ALL_CARDS.filter(c => !SHELVED_IDS.has(c.id)); }

// ═══════ CARD DATA — full roster sorted by ID ═══════
const ALL_CARDS = [
  {id:1,name:"Kodako",rarity:"common",maxHp:6,ability:"Swift",desc:"Roll 1-2-3: negate damage and deal 4 to enemy.",set:"Set 1",art:"../testroom/art/originals/kodako.jpg"},
  {id:2,name:"Nikon",rarity:"common",maxHp:6,ability:"Ambush",desc:"Win first roll: deal triple damage.",set:"Set 1",art:"../testroom/art/originals/nikon.jpg"},
  {id:3,name:"Ancient Librarian",rarity:"common",maxHp:6,ability:"Knowledge",desc:"For each 2 rolled by both players, add +1 damage if you deal damage.",set:"Set 1",art:"../testroom/art/originals/AncientLibrarian.png"},
  {id:4,name:"Wanderer",rarity:"common",maxHp:8,ability:"Curiosity",desc:"Roll a straight (consecutive sequence, no repeats): deal +2 damage.",set:"Set 1",art:"../testroom/art/originals/Wanderer.png"},
  {id:5,name:"Puff",rarity:"common",maxHp:6,ability:"Cute",desc:"Enemy doubles and triples do -1 damage.",set:"Set 1",art:"../testroom/art/originals/Puff.png"},
  {id:6,name:"Fang Outside",rarity:"common",maxHp:2,ability:"Skillful Coward",desc:"When Fang wins a roll, you may switch with a ghost on your sideline after damage.",set:"Set 1",art:"../testroom/art/originals/FangOutside.png"},
  {id:7,name:"Fang Undercover",rarity:"common",maxHp:2,ability:"Skilled Coward",desc:"When taking damage, you may switch this ghost with any of your sideline ghosts and negate damage.",set:"Set 1",art:"../testroom/art/originals/FangUndercover.png"},
  {id:8,name:"Buttons",rarity:"common",maxHp:1,ability:"Perfect Plan",desc:"If Buttons rolls triple 6\'s, deal +15 damage.",set:"Set 1",art:"../testroom/art/originals/Buttons.png"},
  {id:9,name:"Little Boo",rarity:"common",maxHp:2,ability:"Mercy",desc:"Enemy rolled triples count as a 1,2,3 roll instead.",set:"Set 1",art:"../testroom/art/originals/LittleBoo.png"},
  {id:10,name:"Patrick",rarity:"common",maxHp:3,ability:"Stone Form",desc:"Don\'t roll. If opponent rolls singles: negate damage, deal 3.",set:"Set 1",art:"../testroom/art/originals/patrick.jpg"},
  {id:11,name:"Villager",rarity:"common",maxHp:4,ability:"Hospitality",desc:"While on the sideline, the ghost in battle gains +1 health every winning roll.",set:"Set 1",art:"../testroom/art/originals/Villager.png"},
  {id:12,name:"Dupy",rarity:"common",maxHp:4,ability:"Frolic",desc:"Rolling a tie instant KOs the opposing ghost.",set:"Set 1",art:"../testroom/art/originals/Dupy.png"},
  {id:13,name:"Shoo",rarity:"common",maxHp:4,ability:"Alpine Air",desc:"If on the sideline, the ghost in play gains +2 health when their health is less than 4. Only Once Per Ghost.",set:"Set 1",art:"../testroom/art/originals/Shoo.png"},
  {id:14,name:"Jeffery",rarity:"common",maxHp:5,ability:"Chuckle",desc:"If on sideline and your ghost wins a battle, ghost in play gains 3 HP.",set:"Set 1",art:"../testroom/art/originals/Jeffery.png"},
  {id:15,name:"Winston",rarity:"common",maxHp:5,ability:"Scheme",desc:"Win: you may swap your opponent\'s ghost with one from their sideline. Gain +2 dice next roll.",set:"Set 1",art:"../testroom/art/originals/Winston.png"},
  {id:16,name:"Chip",rarity:"common",maxHp:4,ability:"Acrobatic Dive",desc:"Your even rolled doubles add +3 damage if you deal damage.",set:"Set 1",art:"../testroom/art/originals/Chip.png"},
  {id:17,name:"Boo Brothers",rarity:"common",maxHp:5,ability:"Teamwork",desc:"Before rolling, may remove 1 die to gain 1 HP.",set:"Set 1",art:"../testroom/art/originals/boo_brothers.jpg"},
  {id:18,name:"Charlie",rarity:"common",maxHp:4,ability:"Rush",desc:"Double 2\'s hit for 7.",set:"Set 1",art:"../testroom/art/originals/Charlie.png"},
  {id:19,name:"Scallywags",rarity:"common",maxHp:5,ability:"Frenzy",desc:"If your rolled dice are all under 4 each, gain +1 die next turn + 1 Surge.",set:"Dark Castle",art:"../testroom/art/originals/Scallywags.png"},
  {id:20,name:"Floop",rarity:"common",maxHp:4,ability:"Muck",desc:"Enemy loses a dice for the following turn if they roll doubles.",set:"Dark Castle",art:"../testroom/art/originals/Floop.png"},
  {id:21,name:"Needle",rarity:"common",maxHp:7,ability:"Big Bro",desc:"While on the sideline, if Buttons is in play, you may roll +1 dice.",set:"Dark Castle",art:"../testroom/art/originals/Needle_dc.png"},
  {id:22,name:"Ancient One",rarity:"common",maxHp:7,ability:"Friend to All",desc:"While on the sideline, give your ghost in play +3 health upon ties.",set:"Dark Castle",art:"../testroom/art/originals/ancient_one.jpg"},
  {id:23,name:"Powder",rarity:"common",maxHp:5,ability:"Final Gift",desc:"When defeated, gain 3 Ice Shards for your next ghost.",set:"Frost Valley",art:"../testroom/art/originals/powder.jpg"},
  {id:24,name:"Simon",rarity:"common",maxHp:7,ability:"Brew Time",desc:"Gain 2 Sacred Fire when taking before-roll damage. Gain 2 Sacred Fire when the enemy rolls triples or better.",set:"Frost Valley",art:"../testroom/art/originals/simon.jpg"},
  {id:25,name:"Cameron",rarity:"common",maxHp:6,ability:"Unstoppable Force",desc:"If the opponent uses a special, Cameron gains +1 die immediately.\\nCameron\'s damage cannot be negated.",set:"Frost Valley",art:"../testroom/art/originals/cameron.jpg"},
  {id:26,name:"Logey",rarity:"common",maxHp:4,ability:"Heinous",desc:"Opponent\'s 5+ dice are unavailable next roll.",set:"Frost Valley",art:"../testroom/art/originals/logey.jpg"},
  {id:27,name:"Fredrick",rarity:"common",maxHp:5,ability:"Careful",desc:"Opponent may only roll up to 3 dice.",set:"Frost Valley",art:"../testroom/art/originals/fredrick.jpg"},
  {id:28,name:"Dream Cat",rarity:"common",maxHp:4,ability:"Jinx",desc:"Both roll doubles: gain +1 die next turn.",set:"Frost Valley",art:"../testroom/art/originals/dream_cat.jpg"},
  {id:29,name:"Sad Sal",rarity:"common",maxHp:5,ability:"Tough Job",desc:"Lose a roll: gain 1 Ice Shard.",set:"Frost Valley",art:"../testroom/art/originals/sad_sal.jpg"},
  {id:30,name:"Tommy Salami",rarity:"common",maxHp:6,ability:"Regulator",desc:"When you roll a 6, gain +1 die and roll it immediately. Repeats as long as you keep rolling 6s.",set:"Frost Valley",art:"../testroom/art/originals/tommy_salami_new.png"},
  {id:31,name:"Gus",rarity:"common",maxHp:6,ability:"Gale Force",desc:"Win: you may force your opponent to swap their active ghost. The new ghost takes the damage.",set:"Frost Valley",art:"../testroom/art/originals/gus.jpg"},
  {id:32,name:"Lou",rarity:"common",maxHp:7,ability:"Bros",desc:"While on the sideline, Grawr gains +1 Damage and +1 Health on Winning Rolls.",set:"Frost Valley",art:"../testroom/art/originals/lou.jpg"},
  {id:33,name:"Sandwiches",rarity:"common",maxHp:6,ability:"Dependable",desc:"While on the sideline, if your opponent gains a Special, you gain it as well.",set:"Frost Valley",art:"../testroom/art/originals/sandwiches.jpg"},
  {id:34,name:"Grawr",rarity:"uncommon",maxHp:7,ability:"Menace",desc:"When Grawr enters the battle, deal 1 damage to the opponent.",set:"Set 1",art:"../testroom/art/originals/Grawr.png"},
  {id:35,name:"Larry",rarity:"uncommon",maxHp:6,ability:"Flying Kick",desc:"Triples deal 3X damage.",set:"Set 1",art:"../testroom/art/originals/Larry.png"},
  {id:36,name:"Bill & Bob",rarity:"uncommon",maxHp:6,ability:"Bait n Switch",desc:"While below 4 health, deal 2X damage on winning rolls.",set:"Set 1",art:"../testroom/art/originals/Bill&Bob.png"},
  {id:37,name:"Dealer",rarity:"uncommon",maxHp:5,ability:"House Rules",desc:"Roll a straight: +3 damage and negate all incoming damage.",set:"Set 1",art:"../testroom/art/originals/Dealer.png"},
  {id:38,name:"Alucard",rarity:"uncommon",maxHp:4,ability:"Colony Call",desc:"Doubles deal +2 damage for each ghost on your sideline. Once Per Game.",set:"Set 1",art:"../testroom/art/originals/Alucard.png"},
  {id:39,name:"Castle Guards",rarity:"uncommon",maxHp:7,ability:"Flamethrower",desc:"Any 3\'s you roll multiplies Castle Guard\'s damage by 2 each.",set:"Set 1",art:"../testroom/art/originals/CastleGuards.png"},
  {id:40,name:"Team Zippy",rarity:"uncommon",maxHp:7,ability:"Teamwork",desc:"Any single damage you inflict deals +2 damage.",set:"Set 1",art:"../testroom/art/originals/TeamZippy.png"},
  {id:41,name:"Guard Thomas",rarity:"uncommon",maxHp:6,ability:"Stoic",desc:"Below 6 HP: immune to singles damage.",set:"Set 1",art:"../testroom/art/originals/guard_thomas.jpg"},
  {id:42,name:"Doc",rarity:"uncommon",maxHp:2,ability:"Savage",desc:"+5 damage when you roll doubles.",set:"Set 1",art:"../testroom/art/originals/Doc.png"},
  {id:43,name:"Outlaw",rarity:"uncommon",maxHp:5,ability:"Thief",desc:"Roll doubles: remove 1 opponent die next turn.",set:"Set 1",art:"../testroom/art/originals/outlaw.jpg"},
  {id:44,name:"Bubble Boys",rarity:"uncommon",maxHp:9,ability:"Pop",desc:"If the enemy rolls triples, Bubble Boys are defeated.",set:"Set 1",art:"../testroom/art/originals/bubble_boys.jpg"},
  {id:45,name:"Cornelius",rarity:"uncommon",maxHp:2,ability:"Antidote",desc:"While on the sideline, negate all enemy sideline effects.",set:"Set 1",art:"../testroom/art/originals/Cornelius.png"},
  {id:46,name:"Cave Dweller",rarity:"uncommon",maxHp:7,ability:"Lurk",desc:"Deal 3X damage on first roll win.",set:"Set 1",art:"../testroom/art/originals/cave_dweller.jpg"},
  {id:47,name:"Hermit",rarity:"uncommon",maxHp:3,ability:"Solitude",desc:"Upon entry, gain +2 health for each ghost defeated on both teams.",set:"Set 1",art:"../testroom/art/originals/Hermit.png"},
  {id:48,name:"Opa",rarity:"uncommon",maxHp:5,ability:"Rest",desc:"If Opa wins the roll or ties, gain +1 health.",set:"Set 1",art:"../testroom/art/originals/Opa.png"},
  {id:49,name:"Greg",rarity:"uncommon",maxHp:5,ability:"Chase",desc:"If Greg has more health than the opposing ghost, Greg\'s rolls do x2 damage.",set:"Set 1",art:"../testroom/art/originals/Greg.png"},
  {id:50,name:"Jackson",rarity:"uncommon",maxHp:3,ability:"Regrow",desc:"After your roll, you may remove 1 of Jackson\'s health to reroll 1 of the dice.",set:"Set 1",art:"../testroom/art/originals/Jackson.png"},
  {id:51,name:"Nicholas",rarity:"uncommon",maxHp:1,ability:"Sneak Attack",desc:"While on the sideline, deal 2 damage to the enemy ghost when they enter play.",set:"Dark Castle",art:"../testroom/art/originals/nicholas.jpg"},
  {id:52,name:"Hugo",rarity:"uncommon",maxHp:5,ability:"Wreckage",desc:"Your opponent loses 1 die their next roll when Hugo takes roll damage.",set:"Dark Castle",art:"../testroom/art/originals/Hugo.png"},
  {id:53,name:"Bogey",rarity:"uncommon",maxHp:5,ability:"Bogus",desc:"When damage would hit Bogey, you may reflect it back at the attacker. Once per game.",set:"Frost Valley",art:"../testroom/art/originals/bogey.jpg"},
  {id:54,name:"Roger",rarity:"uncommon",maxHp:6,ability:"Tempest",desc:"Roll 2 pairs of doubles (4+ dice): gain 3 Sacred Fires.",set:"Frost Valley",art:"../testroom/art/originals/roger.jpg"},
  {id:55,name:"Masked Hero",rarity:"uncommon",maxHp:5,ability:"Underdog",desc:"Immune to before-roll damage. Gain +1 Burn for each 3 you roll.",set:"Frost Valley",art:"../testroom/art/originals/masked_hero.jpg"},
  {id:56,name:"Chad",rarity:"common",maxHp:6,ability:"Sploop!",desc:"On entry, gain 2 Ice Shards.",set:"Frost Valley",art:"../testroom/art/originals/chad.jpg"},
  {id:57,name:"Marcus",rarity:"uncommon",maxHp:7,ability:"Glacial Pounding",desc:"Take 3+ damage: YOU gain 4 extra dice on the next roll.",set:"Frost Valley",art:"../testroom/art/originals/marcus.jpg"},
  {id:58,name:"Ashley",rarity:"uncommon",maxHp:3,ability:"Burning Soul",desc:"Win a roll: gain 1 Sacred Fire.",set:"Frost Valley",art:"../testroom/art/originals/ashley.jpg"},
  {id:59,name:"Mr Filbert",rarity:"common",maxHp:6,ability:"Mask Merchant",desc:"While on the sideline, any healing instead deals damage to the intended ghost.",set:"Frost Valley",art:"../testroom/art/originals/mr_filbert.jpg"},
  {id:60,name:"Dallas",rarity:"uncommon",maxHp:4,ability:"Quick Draw",desc:"When coming off the sideline, steal 1 of your opponents die for the first 2 rolls.",set:"Frost Valley",art:"../testroom/art/originals/dallas.jpg"},
  {id:61,name:"Suspicious Jeff",rarity:"uncommon",maxHp:4,ability:"Snicker",desc:"While on the sideline, if your Ghost wins a battle, steal 1 of the enemy dice next roll.",set:"Frost Valley",art:"../testroom/art/originals/suspicious_jeff.jpg"},
  {id:62,name:"Raditz",rarity:"rare",maxHp:6,ability:"Hunt",desc:"When Raditz enters the battle, you may switch the opposing ghost with a different ghost from their sideline.",set:"Set 1",art:"../testroom/art/originals/Raditz.png"},
  {id:63,name:"Doug",rarity:"rare",maxHp:3,ability:"Caution",desc:"Before rolling, Doug may switch with a sideline ghost once per game. Then, gain +1 dice your next roll.",set:"Set 1",art:"../testroom/art/originals/Doug.png"},
  {id:64,name:"Sparky",rarity:"rare",maxHp:4,ability:"Tinder",desc:"Your rolled 1\'s add +3 damage each if you deal damage.",set:"Set 1",art:"../testroom/art/originals/Sparky.png"},
  {id:65,name:"Wim",rarity:"rare",maxHp:6,ability:"Slash",desc:"+5 damage when all dice are odd.",set:"Set 1",art:"../testroom/art/originals/wim.jpg"},
  {id:66,name:"Munch",rarity:"rare",maxHp:6,ability:"Scraps",desc:"Upon defeating a ghost, gain 4 health.",set:"Set 1",art:"../testroom/art/originals/Munch.png"},
  {id:67,name:"Snorton",rarity:"rare",maxHp:8,ability:"Fissure",desc:"+5 damage if you roll at least two 6\'s and deal damage.",set:"Set 1",art:"../testroom/art/originals/snorton.jpg"},
  {id:68,name:"Kairan",rarity:"rare",maxHp:4,ability:"Let\'s Dance",desc:"Roll doubles: +1 die next roll.",set:"Set 1",art:"../testroom/art/originals/kairan.jpg"},
  {id:69,name:"Sonya",rarity:"rare",maxHp:3,ability:"Mesmerize",desc:"You may change one of your dice results to a 2 each roll.",set:"Set 1",art:"../testroom/art/originals/Sonya.png"},
  {id:70,name:"Katrina",rarity:"rare",maxHp:5,ability:"Seeker",desc:"Before rolling, if you have less HP than the enemy, gain 1 HP.",set:"Set 1",art:"../testroom/art/originals/katrina.jpg"},
  {id:71,name:"Admiral",rarity:"rare",maxHp:3,ability:"Comrades",desc:"While on the sideline, +2 damage to your even doubles rolls.",set:"Set 1",art:"../testroom/art/originals/Admiral.png"},
  {id:72,name:"Sky",rarity:"rare",maxHp:4,ability:"Elusive",desc:"If incoming damage is greater than 2, the damage is negated.",set:"Set 1",art:"../testroom/art/originals/Sky.png"},
  {id:73,name:"Stone Cold",rarity:"rare",maxHp:7,ability:"One-two-one!",desc:"Roll double 1\'s: deal 3X damage.",set:"Set 1",art:"../testroom/art/originals/stone_cold.jpg"},
  {id:74,name:"Dark Jeff",rarity:"rare",maxHp:3,ability:"Cackle",desc:"While on the sideline, +1 damage to all your rolls.",set:"Set 1",art:"../testroom/art/originals/DarkJeff.png"},
  {id:75,name:"Flora",rarity:"rare",maxHp:4,ability:"Restore",desc:"Roll doubles: +2 HP after damage is applied.",set:"Set 1",art:"../testroom/art/originals/flora.jpg"},
  {id:76,name:"Dark Wing",rarity:"rare",maxHp:2,ability:"Precision",desc:"Once per game, if Dark Wing rolls singles, he may reroll all his dice.",set:"Set 1",art:"../testroom/art/originals/DarkWing.png"},
  {id:77,name:"City Cyboo",rarity:"rare",maxHp:1,ability:"Barrier",desc:"Takes no damage from Enemy Doubles.",set:"Set 1",art:"../testroom/art/originals/CityCyboo.png"},
  {id:78,name:"Haywire",rarity:"rare",maxHp:7,ability:"Wild Chords",desc:"Upon rolling triples or better: gain 1 permanent die. Haywire gains +2 permanent damage. Once per game.",set:"Dark Castle",art:"../testroom/art/originals/Haywire.png"},
  {id:79,name:"Laura",rarity:"rare",maxHp:4,ability:"Catchy Tune",desc:"Roll a straight to unlock Catchy Tune. Catchy Tune: choose one die after each roll to lock for the next roll.",set:"Rolling Hills",art:"../testroom/art/originals/laura.jpg"},
  {id:80,name:"Bilbo",rarity:"rare",maxHp:2,ability:"Little Buddy",desc:"While on the sideline, your ghost in play gains +2 damage if you roll singles.",set:"Dark Castle",art:"../testroom/art/originals/bilbo.jpg"},
  {id:81,name:"Spockles",rarity:"rare",maxHp:6,ability:"Valley Magic",desc:"Win a roll: gain 2 Ice Shards.",set:"Frost Valley",art:"../testroom/art/originals/spockles.jpg"},
  {id:82,name:"Antoinette",rarity:"uncommon",maxHp:6,ability:"Grace",desc:"Roll as many dice as your opponent rolls. +1 Damage on doubles.",set:"Frost Valley",art:"../testroom/art/originals/antoinette.jpg"},
  {id:83,name:"Troubling Haters",rarity:"uncommon",maxHp:3,ability:"Growing Mob",desc:"Deal 4+ damage in a turn: gain +2 HP.",set:"Frost Valley",art:"../testroom/art/originals/troubling_haters.jpg"},
  {id:84,name:"Wandering Sue",rarity:"uncommon",maxHp:4,ability:"Hidden Weakness",desc:"If enemy has 12+ HP, destroy them before rolling.",set:"Frost Valley",art:"../testroom/art/originals/wandering_sue.jpg"},
  {id:85,name:"Eloise",rarity:"rare",maxHp:5,ability:"Change of Heart",desc:"Spend 1 Ice Shard to swap HP with enemy before rolling.",set:"Frost Valley",art:"../testroom/art/originals/eloise.jpg"},
  {id:86,name:"Pelter",rarity:"rare",maxHp:5,ability:"Snowball",desc:"Doubles gain +2 damage.",set:"Frost Valley",art:"../testroom/art/originals/pelter.jpg"},
  {id:87,name:"Zach",rarity:"rare",maxHp:7,ability:"Craftsman",desc:"While on the sideline, Guard Thomas gains +3 damage on Doubles.",set:"Frost Valley",art:"../testroom/art/originals/zach.jpg"},
  {id:88,name:"Pale Nimbus",rarity:"rare",maxHp:4,ability:"Hidden Storm",desc:"While on the sideline, add +2 Damage if your total roll result adds to less than 7.",set:"Frost Valley",art:"../testroom/art/originals/pale_nimbus.jpg"},
  {id:89,name:"Mallow",rarity:"rare",maxHp:5,ability:"Dozy Cozy",desc:"While on the sideline, before rolling you may spend 2 Sacred Fire to give your Ghost in Play 3 Health and gain 1 Burn.",set:"Frost Valley",art:"../testroom/art/originals/mallow.jpg"},
  {id:90,name:"Jeanie",rarity:"rare",maxHp:4,ability:"Hidden Treasure",desc:"While on the sideline, you may force the opponent to reroll all their dice. Once Per Game.",set:"Frost Valley",art:"../testroom/art/originals/jeanie.jpg"},
  {id:91,name:"Calvin & Anna",rarity:"rare",maxHp:6,ability:"Toboggan",desc:"When you defeat a Ghost, you may switch Calvin & Anna with a ghost from your sideline.",set:"Frost Valley",art:"../testroom/art/originals/calvin_anna.jpg"},
  {id:92,name:"Gary",rarity:"rare",maxHp:6,ability:"Lucky Novice",desc:"Sideline & In Play, gain +2 Ice Shards for each 1 you roll.",set:"Frost Valley",art:"../testroom/art/originals/gary.jpg"},
  {id:93,name:"Bandit Pete",rarity:"uncommon",maxHp:5,ability:"Bandit",desc:"While on the Sideline, if either player rolls only 2 dice, your ghost in play gains +3 Damage.",set:"Frost Valley",art:"../testroom/art/originals/bandit_pete.jpg"},
  {id:94,name:"Jenkins",rarity:"ghost-rare",maxHp:5,ability:"Greeting",desc:"When Jenkins enters the battle, roll 4 dice to inflict damage once.",set:"Set 1",art:"../testroom/art/originals/Jenkins.png"},
  {id:95,name:"Tabitha",rarity:"ghost-rare",maxHp:1,ability:"Rally",desc:"While on the sideline, +2 damage to your doubles rolls.",set:"Set 1",art:"../testroom/art/originals/Tabitha.png"},
  {id:96,name:"Hector",rarity:"ghost-rare",maxHp:6,ability:"Protector",desc:"Singles beat doubles. +1 damage on singles.",set:"Dark Castle",art:"../testroom/art/originals/hector.jpg"},
  {id:97,name:"Toby",rarity:"ghost-rare",maxHp:7,ability:"Pure Heart",desc:"Before rolling you may declare the final roll. Toby is defeated next turn before rolling. Winning this roll defeats the enemy ghost.",set:"Dark Castle",art:"../testroom/art/originals/Toby.png"},
  {id:98,name:"Redd",rarity:"ghost-rare",maxHp:7,ability:"Notorious",desc:"When Redd enters the battle, gain +2 dice this roll.",set:"Dark Castle",art:"../testroom/art/originals/Redd.png"},
  {id:99,name:"Guardian Fairy",rarity:"ghost-rare",maxHp:3,ability:"Wish",desc:"Sideline: when your active ghost is about to take damage, Guardian Fairy can leap in and take the hit instead.",set:"Set 1",art:"../testroom/art/originals/GuardianFairy.png"},
  {id:100,name:"Cyboo",rarity:"ghost-rare",maxHp:3,ability:"Spark",desc:"While on the sideline, your ghost in play gains +1 dice if they have less than 3 health.",set:"Set 1",art:"../testroom/art/originals/Cyboo.png"},
  {id:101,name:"Splinter",rarity:"ghost-rare",maxHp:4,ability:"Toxic Fumes",desc:"After winning a roll, deal 1 damage before every roll.",set:"Set 1",art:"../testroom/art/originals/Splinter.png"},
  {id:103,name:"Night Master",rarity:"ghost-rare",maxHp:5,ability:"Bullseye",desc:"If you roll doubles and win the roll, immediately destroy a ghost on the enemy sideline that has less than 4 HP.",set:"Frost Valley",art:"../testroom/art/originals/night_master.jpg"},
  {id:104,name:"Skylar",rarity:"ghost-rare",maxHp:7,ability:"Winter Barrage",desc:"Ice Shards deal +2 damage instead of +1.",set:"Frost Valley",art:"../testroom/art/originals/skylar.jpg"},
  {id:105,name:"Tyler",rarity:"ghost-rare",maxHp:7,ability:"Heating Up",desc:"Before rolling, spend 2 HP to gain +1 die. Sacred Fires deal x2.",set:"Frost Valley",art:"../testroom/art/originals/tyler.jpg"},
  {id:106,name:"King Jay",rarity:"ghost-rare",maxHp:7,ability:"Reflection",desc:"Lose roll & dice total = 7: reflect all damage.",set:"Frost Valley",art:"../testroom/art/originals/king_jay.jpg"},
  {id:107,name:"Piper",rarity:"ghost-rare",maxHp:6,ability:"Slick Coat",desc:"Negate enemy before-rolling effects. -1 enemy die next roll. Win with singles: gain 1 Sacred Fire.",set:"Frost Valley",art:"../testroom/art/originals/piper.jpg"},
  {id:108,name:"Lucy",rarity:"legendary",maxHp:8,ability:"Blue Fire",desc:"Win: gain 1 Sacred Fire.",set:"Dark Castle",art:"../testroom/art/originals/lucy.jpg"},
  {id:109,name:"Bo",rarity:"legendary",maxHp:5,ability:"Miracle",desc:"Upon defeating a Ghost, return one of your defeated Ghosts to your sideline. Gain 1 Magic Firefly.",set:"Set 1",art:"../testroom/art/originals/Bo.png"},
  {id:110,name:"The Mountain King",rarity:"legendary",maxHp:9,ability:"Beast Mode",desc:"Doubles deal 2X damage.",set:"Set 1",art:"../testroom/art/originals/mountain_king_leg.jpg"},
  {id:111,name:"Shade",rarity:"legendary",maxHp:5,ability:"Haunt",desc:"Before each roll, opponent takes 1 damage.",set:"Set 1",art:"../testroom/art/originals/shade.jpg"},
  {id:112,name:"Doom",rarity:"legendary",maxHp:7,ability:"Fiendship",desc:"+2 bonus damage!",set:"Set 1",art:"../testroom/art/originals/doom.jpg"},
  {id:113,name:"Prince Balatron",rarity:"legendary",maxHp:6,ability:"Party Time",desc:"Lose a roll & survive: roll 1 counter die for damage.",set:"Frost Valley",art:"../testroom/art/originals/balatron.jpg"},
  {id:114,name:"Romy",rarity:"legendary",maxHp:8,ability:"Valley Guardian",desc:"Predict a die number. If any die matches: +3 damage.",set:"Frost Valley",art:"../testroom/art/originals/romy.jpg"},
  {id:201,name:"Bouril",rarity:"common",maxHp:10,ability:"Slumber",desc:"Entry: your first roll is automatically 1-2-3.",set:"Volcanic Isles",art:"../testroom/art/old_hank.jpg"},
  {id:202,name:"Dark Fang",rarity:"rare",maxHp:5,ability:"Pressure",desc:"While active: enemy ghost cannot heal or gain HP. Win: deal +1 damage for each KO\'d ghost this game (both teams).",set:"Rolling Hills",art:"../testroom/art/originals/DarkFang.png"},
  {id:203,name:"Benjamin",rarity:"uncommon",maxHp:3,ability:"Magic Touch",desc:"Once per turn: use the Moonstone special without discarding it.",set:"Volcanic Isles",art:"../testroom/art/benny.jpg"},
  {id:204,name:"Finn",rarity:"rare",maxHp:6,ability:"Forge",desc:"Sideline & In Play: discard 1 Healing Seed and 1 Sacred Fire to forge the Flame Blade.",set:"Rolling Hills",art:"../testroom/art/finn.png"},
  {id:205,name:"Shade\'s Shadow",rarity:"rare",maxHp:1,ability:"Meltdown",desc:"Sideline: before each roll, if the enemy active ghost has less than 4 HP, deal 1 damage.",set:"Volcanic Isles",art:"../testroom/art/kaboom.png"},
  {id:206,name:"Zain",rarity:"ghost-rare",maxHp:6,ability:"Ice Blade",desc:"Win a roll: gain 1 Ice Shard. Sideline & In Play: discard 1 Ice Shard and 1 Moonstone to forge the Ice Blade.",set:"Volcanic Isles",art:"../testroom/art/echo.png"},
  {id:207,name:"Hank",rarity:"common",maxHp:7,ability:"Tremor",desc:"Each 4 you roll: gain 1 Lucky Stone.",set:"Volcanic Isles",art:"../testroom/art/stomper.png"},
  {id:208,name:"Happy Crystal",rarity:"common",maxHp:2,ability:"Spark Strike",desc:"Before rolling: you may sacrifice Happy Crystal to gain 1 Moonstone.",set:"Volcanic Isles",art:"../testroom/art/clover.jpg"},
  {id:209,name:"Dart",rarity:"common",maxHp:3,ability:"Plunder",desc:"Win: gain 2 Surge.",set:"Volcanic Isles",art:"../testroom/art/swipers.png"},
  {id:210,name:"Timber",rarity:"legendary",maxHp:6,ability:"Howl",desc:"While Timber is active, before rolling: opponent must choose — discard 2 specials OR remove 1 die for this roll.",set:"Rolling Hills",art:"../testroom/art/timber.jpg"},
  {id:301,name:"Dylan",rarity:"common",maxHp:3,ability:"Sun Song",desc:"Sideline & In Play: enemy before-roll effects don\'t activate. On winning rolls, gain 1 Burn.",set:"Rolling Hills",art:"../testroom/art/haystack_hank.jpg"},
  {id:302,name:"Maximo",rarity:"common",maxHp:4,ability:"Nap",desc:"Entry: roll only 1 die on your first roll. After each round: gain 1 Healing Seed and 1 Lucky Stone.",set:"Rolling Hills",art:"../testroom/art/toadstool.jpg"},
  {id:303,name:"Tweak and Twonk",rarity:"common",maxHp:6,ability:"Roaring Crowd",desc:"Sideline: if your active ghost ties, gain 4 Surge.",set:"Rolling Hills",art:"../testroom/art/nugget.jpg"},
  {id:304,name:"The Ember Force",rarity:"uncommon",maxHp:3,ability:"Swarm",desc:"Before rolling: deal 1 damage to the enemy active ghost.",set:"Volcanic Isles",art:"../testroom/art/the_flickers.jpg"},
  {id:305,name:"Selene",rarity:"legendary",maxHp:6,ability:"Heart of the Hills",desc:"Roll doubles: choose — gain 2 Healing Seeds OR 3 Lucky Stones.",set:"Rolling Hills",art:"../testroom/art/luna.jpg"},
  {id:306,name:"Nerina",rarity:"legendary",maxHp:9,ability:"Leviathan",desc:"Entry: deal 3 damage to the enemy active ghost.",set:"Volcanic Isles",art:"../testroom/art/the_deep.jpg"},
  {id:307,name:"Artemis",rarity:"rare",maxHp:3,ability:"Daughter of the Stream",desc:"Win: gain 3 Ice Shards.",set:"Rolling Hills",art:"../testroom/art/dewdrop.webp"},
  {id:308,name:"Kaplan",rarity:"uncommon",maxHp:5,ability:"Pollinate",desc:"When opponent rolls doubles: gain 1 Healing Seed.",set:"Rolling Hills",art:"../testroom/art/honeybun.jpg"},
  {id:309,name:"Aunt Susan",rarity:"uncommon",maxHp:4,ability:"Harvest Dance",desc:"Discard 1 Healing Seed: deal +2 damage. Win: +2 Healing Seeds.",set:"Rolling Hills",art:"../testroom/art/rustler.jpg"},
  {id:310,name:"Granny",rarity:"uncommon",maxHp:3,ability:"Bedtime Story",desc:"Sideline: when one of your ghosts is defeated — by singles: gain 2 Lucky Stones. By doubles: gain 1 Moonstone. By triples or better: gain 3 Sacred Fires.",set:"Rolling Hills",art:"../testroom/art/granny.jpg"},
  {id:311,name:"Pudge",rarity:"common",maxHp:7,ability:"Belly Flop",desc:"Doubles: deal +2 damage. After damage is applied, you take 1 damage.",set:"Rolling Hills",art:"../testroom/art/pudge.webp"},
  {id:312,name:"Timpleton",rarity:"uncommon",maxHp:4,ability:"Big Target",desc:"Win a roll: deal +3 damage if the enemy ghost\'s HP is higher than Timpleton\'s.",set:"Rolling Hills",art:"../testroom/art/lurk.jpg"},
  {id:313,name:"Sylvia",rarity:"rare",maxHp:4,ability:"Porpoise",desc:"Ice Shards cost nothing to commit. When you lose a roll: roll 1 die. If you roll a 5 or 6, negate all damage.",set:"Volcanic Isles",art:"../testroom/art/ripple.jpg"},
  {id:314,name:"Farmer Jeff",rarity:"ghost-rare",maxHp:5,ability:"Harvest",desc:"Sideline & In Play: gain 1 Healing Seed for each 6 you roll.",set:"Rolling Hills",art:"../testroom/art/farmer_jeff.jpg"},
  {id:315,name:"Harrison",rarity:"rare",maxHp:7,ability:"Ascend",desc:"Discard Healing Seeds: roll 1 extra die per seed discarded.",set:"Rolling Hills",art:"../testroom/art/moonreach.jpg"},
  {id:316,name:"Penny",rarity:"common",maxHp:4,ability:"Forager",desc:"Win: gain 1 Healing Seed.",set:"Rolling Hills",art:"../testroom/art/penny.webp"},
  {id:317,name:"Scorch",rarity:"common",maxHp:3,ability:"Singe",desc:"Win: opponent\'s active ghost loses 1 max HP permanently.",set:"Volcanic Isles",art:"../testroom/art/scorch.webp"},
  {id:318,name:"Magnolia",rarity:"uncommon",maxHp:5,ability:"Bloom",desc:"Spend 1 Healing Seed: your active ghost gains +2 damage this round.",set:"Rolling Hills",art:""},
  {id:319,name:"Pumice",rarity:"common",maxHp:4,ability:"Float",desc:"Sideline: if your ghost would take 3+ damage, reduce to 2.",set:"Volcanic Isles",art:"../testroom/art/pumice.webp"},
  {id:320,name:"Bramble",rarity:"common",maxHp:3,ability:"Thorn Wall",desc:"Entry: opponent takes 1 damage next round.",set:"Rolling Hills",art:"../testroom/art/bramble.webp"},
  {id:321,name:"Forge Fire",rarity:"uncommon",maxHp:5,ability:"Temper",desc:"Spend 1 Surge: your next win deals double damage.",set:"Volcanic Isles",art:"../testroom/art/forge_fire.webp"},
  {id:322,name:"Old Mill",rarity:"rare",maxHp:6,ability:"Grindstone",desc:"Spend 1 Surge + 1 Surge: gain 1 Moonstone.",set:"Rolling Hills",art:"../testroom/art/old_mill.webp"},
  {id:323,name:"Char",rarity:"common",maxHp:4,ability:"Afterburn",desc:"Win: deal 1 damage at the start of next round.",set:"Volcanic Isles",art:"../testroom/art/char.webp"},
  {id:324,name:"Biscuit",rarity:"common",maxHp:5,ability:"Warm Up",desc:"Sideline: your active ghost gains +1 HP on wins. Cannot exceed max.",set:"Rolling Hills",art:"../testroom/art/biscuit.webp"},
  {id:325,name:"Magma Heart",rarity:"rare",maxHp:7,ability:"Core Melt",desc:"Below 3 HP: all your damage ignores damage reduction effects.",set:"Volcanic Isles",art:"../testroom/art/magma_heart.webp"},
  {id:326,name:"Barnaby",rarity:"uncommon",maxHp:5,ability:"Stubborn",desc:"Cannot be swapped out by opponent effects. Immune to forced switches.",set:"Rolling Hills",art:"../testroom/art/barnaby.webp"},
  {id:327,name:"Natalia",rarity:"ghost-rare",maxHp:6,ability:"Materialization",desc:"When you roll even doubles (2s, 4s, or 6s): gain 1 Moonstone + 1 Lucky Stone.",set:"Volcanic Isles",art:"../testroom/art/geode.jpg"},
  {id:328,name:"Drizzle",rarity:"common",maxHp:4,ability:"Rain Dance",desc:"Both players reroll all 1s. Free.",set:"Rolling Hills",art:"../testroom/art/drizzle.webp"},
  {id:329,name:"Clink",rarity:"common",maxHp:3,ability:"Prospect",desc:"Win: gain 1 Surge. Lose: gain 1 Surge.",set:"Volcanic Isles",art:"../testroom/art/clink.webp"},
  {id:330,name:"Snoozer",rarity:"common",maxHp:3,ability:"Nap Time",desc:"Sideline: if no damage is dealt in a round, gain 1 Surge.",set:"Rolling Hills",art:"../testroom/art/snoozer.webp"},
  {id:331,name:"Igneous",rarity:"uncommon",maxHp:5,ability:"Crystallize",desc:"Each round you don\'t take damage: gain 1 Surge.",set:"Volcanic Isles",art:"../testroom/art/igneous.webp"},
  {id:332,name:"Grandmother Willow",rarity:"ghost-rare",maxHp:7,ability:"Deep Roots",desc:"Cannot be KO\'d by singles damage. Must be defeated by doubles or triples.",set:"Rolling Hills",art:"../testroom/art/grandmother_willow.webp"},
  {id:333,name:"Smoke Signal",rarity:"common",maxHp:4,ability:"Warning",desc:"Sideline: reveal opponent\'s sideline abilities.",set:"Volcanic Isles",art:"../testroom/art/smoke_signal.webp"},
  {id:334,name:"Fiddle",rarity:"uncommon",maxHp:6,ability:"Hoedown",desc:"Win: you may swap your active ghost without triggering Stomper/Crag effects.",set:"Rolling Hills",art:"../testroom/art/fiddle.webp"},
  {id:335,name:"Soot Sprite",rarity:"rare",maxHp:6,ability:"Scatter",desc:"When hit: split into 2 copies with half HP each. Opponent must KO both.",set:"Volcanic Isles",art:"../testroom/art/soot_sprite.webp"},
  {id:336,name:"Humar",rarity:"legendary",maxHp:5,ability:"Meteor",desc:"Win: opponent takes 2 damage before their next roll. Gain 1 Burn.",set:"Volcanic Isles",art:"../testroom/art/humar.jpg"},
  {id:337,name:"Fuego",rarity:"uncommon",maxHp:5,ability:"Fiesta",desc:"Win with triples: gain 1 of every resource.",set:"Volcanic Isles",art:"../testroom/art/fuego.webp"},
  {id:338,name:"Thistle",rarity:"rare",maxHp:7,ability:"Barbed",desc:"When you take damage: the attacker takes 1 damage back. Always.",set:"Rolling Hills",art:"../testroom/art/thistle.webp"},
  {id:339,name:"Slag Heap",rarity:"common",maxHp:3,ability:"Residue",desc:"When defeated: opponent\'s active ghost cannot heal for 2 rounds.",set:"Volcanic Isles",art:"../testroom/art/slag_heap.webp"},
  {id:340,name:"Cluck",rarity:"common",maxHp:5,ability:"Peck",desc:"Win with singles: deal +2 damage.",set:"Rolling Hills",art:"../testroom/art/cluck.webp"},
  {id:341,name:"Obsidian Throne",rarity:"ghost-rare",maxHp:7,ability:"Dominion",desc:"While active: opponent cannot use items (Surge, Surge, Healing Seeds).",set:"Volcanic Isles",art:"../testroom/art/obsidian_throne.webp"},
  {id:342,name:"Calvin",rarity:"uncommon",maxHp:5,ability:"Overclock",desc:"Win: heal +1 HP (can exceed max HP). Gain +1 Healing Seed.",set:"Rolling Hills",art:"../testroom/art/mossy.webp"},
  {id:343,name:"Boris",rarity:"common",maxHp:6,ability:"Fortify",desc:"When you spend a Surge: Boris gains 2 HP (can exceed max HP).",set:"Volcanic Isles",art:"../testroom/art/bastion.webp"},
  {id:344,name:"Wisp",rarity:"common",maxHp:4,ability:"Guide Light",desc:"Sideline: opponent cannot gain resources this round.",set:"Rolling Hills",art:"../testroom/art/wisp.webp"},
  {id:345,name:"Red Hunter",rarity:"ghost-rare",maxHp:6,ability:"Rumble",desc:"Win a roll: if your opponent has any specials, deal +3 damage.",set:"Volcanic Isles",art:"../testroom/art/tremor.webp"},
  {id:346,name:"Harvest Moon",rarity:"rare",maxHp:6,ability:"Reaping",desc:"Defeat a ghost: gain 1 of every resource (Healing Seed, Surge, Surge).",set:"Rolling Hills",art:"../testroom/art/harvest_moon.webp"},
  {id:347,name:"Eruption",rarity:"rare",maxHp:7,ability:"Blow",desc:"Spend 2 Silver Leaves: deal 4 damage immediately. No roll needed.",set:"Volcanic Isles",art:"../testroom/art/eruption.webp"},
  {id:348,name:"Mulch",rarity:"common",maxHp:3,ability:"Decompose",desc:"When defeated: your team gains 2 Healing Seeds.",set:"Rolling Hills",art:"../testroom/art/mulch.webp"},
  {id:349,name:"Wick",rarity:"uncommon",maxHp:5,ability:"Slow Burn",desc:"Each round: deal 1 damage to opponent. But lose 1 HP yourself.",set:"Volcanic Isles",art:"../testroom/art/wick.webp"},
  {id:350,name:"Silo",rarity:"uncommon",maxHp:6,ability:"Stockpile",desc:"Sideline: at end of each round, store 1 copy of any resource your team gained.",set:"Rolling Hills",art:"../testroom/art/silo.webp"},
  {id:351,name:"Glow Worm",rarity:"common",maxHp:5,ability:"Tunnel",desc:"Spend 1 Surge: switch your active ghost. Free action, no swap triggers.",set:"Volcanic Isles",art:"../testroom/art/glow_worm.webp"},
  {id:352,name:"Jimmy",rarity:"common",maxHp:2,ability:"Chirp",desc:"Sideline & In Play: on a tie, gain 3 Lucky Stones and 1 Magic Firefly.",set:"Rolling Hills",art:"../testroom/art/cricket.webp"},
  {id:353,name:"Molten Mirror",rarity:"rare",maxHp:6,ability:"Reflect Pool",desc:"Opponent\'s resource-spending abilities also cost 1 additional resource.",set:"Volcanic Isles",art:"../testroom/art/molten_mirror.webp"},
  {id:354,name:"Patches",rarity:"uncommon",maxHp:5,ability:"Quilt",desc:"Spend 2 Healing Seeds: negate all damage this round.",set:"Rolling Hills",art:"../testroom/art/patches.webp"},
  {id:355,name:"Puff Ball",rarity:"common",maxHp:3,ability:"Burst",desc:"When hit by doubles: explode for 2 damage to opponent. Then KO yourself.",set:"Volcanic Isles",art:"../testroom/art/puff_ball.webp"},
  {id:356,name:"Riverbed",rarity:"rare",maxHp:7,ability:"Current",desc:"Sideline: if opponent rolls doubles, force them to reroll one die.",set:"Rolling Hills",art:"../testroom/art/riverbed.webp"},
  {id:357,name:"Anvil",rarity:"uncommon",maxHp:6,ability:"Heavy Strike",desc:"Spend 1 Surge: singles deal 3 damage instead of 1 this round.",set:"Volcanic Isles",art:"../testroom/art/anvil.webp"},
  {id:358,name:"Tadpole",rarity:"common",maxHp:5,ability:"Splash",desc:"Entry: gain 1 Surge.",set:"Rolling Hills",art:"../testroom/art/tadpole.webp"},
  {id:359,name:"Volcanic Heart",rarity:"ghost-rare",maxHp:8,ability:"Pulse",desc:"Every 3 rounds: deal 2 damage to ALL ghosts on the field (both teams).",set:"Volcanic Isles",art:"../testroom/art/volcanic_heart.webp"},
  {id:360,name:"The Shepherd",rarity:"legendary",maxHp:8,ability:"Flock",desc:"Your defeated ghosts return to sideline with 1 HP. Once per game.",set:"Rolling Hills",art:"../testroom/art/the_shepherd.webp"},
  {id:361,name:"Ash Phoenix",rarity:"rare",maxHp:4,ability:"Rebirth",desc:"When defeated: return to battle next round with 2 HP. Once per game.",set:"Volcanic Isles",art:"../testroom/art/ash_phoenix.webp"},
  {id:362,name:"Bumble",rarity:"uncommon",maxHp:6,ability:"Pollinate",desc:"Win: give 1 Healing Seed to opponent. But gain 2 yourself.",set:"Rolling Hills",art:"../testroom/art/bumble.webp"},
  {id:363,name:"Pyrope",rarity:"uncommon",maxHp:5,ability:"Gem Armor",desc:"Spend 1 Surge: negate the next instance of damage.",set:"Volcanic Isles",art:"../testroom/art/pyrope.webp"},
  {id:364,name:"Dusk",rarity:"uncommon",maxHp:4,ability:"Twilight",desc:"After round 5: all your damage gains +1.",set:"Rolling Hills",art:"../testroom/art/dusk.webp"},
  {id:365,name:"Tyson",rarity:"common",maxHp:4,ability:"Hop",desc:"Win: choose an enemy sideline ghost. That ghost\'s sideline ability is disabled until it enters play.",set:"Volcanic Isles",art:"../testroom/art/cinder_bunny.png"},
  {id:366,name:"Mother Nature",rarity:"legendary",maxHp:8,ability:"Seasons",desc:"Each round cycles: Spring (+1 HP), Summer (+1 dmg), Autumn (+1 resource), Winter (opponent -1 die).",set:"Rolling Hills",art:"../testroom/art/mother_nature.webp"},
  {id:367,name:"Dragonclaw",rarity:"rare",maxHp:7,ability:"Rake",desc:"Win with 3 different numbers: deal +3 damage.",set:"Volcanic Isles",art:"../testroom/art/dragonclaw.webp"},
  {id:368,name:"Scarecrow King",rarity:"rare",maxHp:4,ability:"Command",desc:"Sideline: all your other sideline ghosts\' abilities trigger twice.",set:"Rolling Hills",art:"../testroom/art/scarecrow_king.webp"},
  {id:401,name:"Knight Terror",rarity:"rare",maxHp:7,ability:"Heavy Air",desc:"While active: after any opponent ability triggers and resolves, the enemy active ghost loses 2 HP.",set:"Dark Castle",art:"../testroom/art/knight_terror.webp"},
  {id:402,name:"Knight Light",rarity:"uncommon",maxHp:6,ability:"Retribution",desc:"While active: when an opponent\'s ability triggers, gain +1 die on your next roll.",set:"Dark Castle",art:"../testroom/art/knight_light.png"},
  {id:403,name:"Smudge",rarity:"rare",maxHp:5,ability:"Blackout",desc:"Before rolling: name a number. If your opponent rolls it, that die doesn\'t count.",set:"Volcanic Isles",art:"../testroom/art/smudge.webp"},
  {id:404,name:"Chagrin",rarity:"uncommon",maxHp:6,ability:"Bitter End",desc:"Lose: gain 1 Surge.",set:"Volcanic Isles",art:"../testroom/art/chagrin.png"},
  {id:406,name:"Fed and Hayden",rarity:"common",maxHp:4,ability:"Eternal Flame",desc:"Sacred Fires are not discarded when used.",set:"Volcanic Isles",art:"../testroom/art/fed_and_hayden.png"},
  {id:409,name:"Nick & Knack",rarity:"common",maxHp:4,ability:"Knick Knack",desc:"Before rolling: you may steal 1 special from the other player. If you do, gain 1 HP and 2 Burn.",set:"Rolling Hills",art:"../testroom/art/originals/Cindergrub.png"},
  {id:410,name:"Mirror Matt",rarity:"common",maxHp:1,ability:"Seven Years",desc:"If the opponent wins with doubles, the damage is reflected to the attacker instead.",set:"Dark Castle",art:"../testroom/art/originals/MirrorMatt.png"},
  {id:413,name:"Sable",rarity:"uncommon",maxHp:6,ability:"Furnace",desc:"Sideline & In Play: Rolling all odd numbers, gain 1 Sacred Fire.",set:"Volcanic Isles",art:"../testroom/art/originals/ObsidianEel.png"},
  {id:414,name:"Chow",rarity:"uncommon",maxHp:5,ability:"Secret Ingredient",desc:"Before rolling: spend 1 Healing Seed to gain +2 dice this roll.",set:"Dark Castle",art:"../testroom/art/originals/Chow.png"},
  {id:415,name:"Nyx & Bessie",rarity:"common",maxHp:6,ability:"Moo! Caw!",desc:"While on the sideline, gain 4 Healing Seeds if you defeat a Ghost.",set:"Rolling Hills",art:"../testroom/art/originals/NyxAndBessie.png"},
  {id:416,name:"Rook",rarity:"uncommon",maxHp:6,ability:"Charcoal",desc:"Immune to Sacred Fire and Burn damage. Win: deal +1 damage per Surge committed this turn.",set:"Volcanic Isles",art:"../testroom/art/originals/Pyroclast.png"},
  {id:417,name:"Twyla",rarity:"rare",maxHp:6,ability:"Lucky Dance",desc:"Each Lucky Stone you spend this turn adds +1 die to your roll and gains +1 Healing Seed.",set:"Rolling Hills",art:"../testroom/art/originals/Hesta.png"},
  {id:418,name:"Pip",rarity:"ghost-rare",maxHp:7,ability:"Toasted",desc:"Upon rolling triples or better: permanently remove 1 die from your opponent for the rest of the game. Pip also gains 2 Sacred Fires. Once per game.",set:"Volcanic Isles",art:"../testroom/art/originals/Pip.png"},
  {id:419,name:"Boopies",rarity:"common",maxHp:3,ability:"Boopie Magic",desc:"Sideline: whenever your active ghost spends a Healing Seed, gain 1 Lucky Stone.",set:"Rolling Hills",art:"../testroom/art/originals/Hedgeling.png"},
  {id:420,name:"Lars",rarity:"common",maxHp:4,ability:"Light the Way",desc:"Entry: gain 1 Surge, 1 Lucky Stone, and 1 Burn.",set:"Dark Castle",art:"../testroom/art/originals/Gourdling.png"},
  {id:423,name:"Zippa",rarity:"uncommon",maxHp:5,ability:"Glimmer",desc:"Before rolling: gain 1 Lucky Stone for each Healing Seed your team currently holds.",set:"Rolling Hills",art:"../testroom/art/originals/Beewick.png"},
  {id:424,name:"Bigsby",rarity:"uncommon",maxHp:5,ability:"Omen",desc:"Win: deal +1 damage. If you use a Moonstone, you must sacrifice Bigsby and replace him with Doom.",set:"Dark Castle",art:"../testroom/art/originals/Digby.png"},
  {id:426,name:"Chester",rarity:"uncommon",maxHp:5,ability:"Well Read",desc:"Win: gain 1 Healing Seed. Win with doubles or better: gain 1 Burn instead.",set:"Rolling Hills",art:"../testroom/art/originals/Chester.png"},
  {id:427,name:"Garrick",rarity:"uncommon",maxHp:5,ability:"Watchfire",desc:"Lose: take -1 damage. Gains 1 Sacred Fire if he defeats a Spiritkin.",set:"Dark Castle",art:"../testroom/art/originals/Brock.png"},
  {id:428,name:"Jasper",rarity:"rare",maxHp:5,ability:"Flame Dive",desc:"Win: roll 1 bonus die. Deal its value as additional damage. Jasper takes 1 damage.",set:"Rolling Hills",art:"../testroom/art/originals/Pickwick.png"},
  {id:429,name:"Young Cap",rarity:"uncommon",maxHp:4,ability:"Energize",desc:"Before rolling: when you use a Healing Seed, also gain +1 die, +1 Ice Shard, and +1 Surge this roll.",set:"Rolling Hills",art:"../testroom/art/originals/OldCap.png"},
  {id:430,name:"Gordok",rarity:"uncommon",maxHp:6,ability:"River Terror",desc:"Win: you may take 2 specials from your opponent instead of dealing damage. Gain +1 die next roll and +1 Moonstone.",set:"Rolling Hills",art:"../testroom/art/originals/Millicent.png"},
  {id:431,name:"Pal Al",rarity:"ghost-rare",maxHp:3,ability:"Squall",desc:"Win: you may gain 4 Ice Shards instead of dealing damage.",set:"Rolling Hills",art:"../testroom/art/originals/TheOvercast.png"},
  {id:432,name:"Valkin the Grand",rarity:"legendary",maxHp:8,ability:"Grand Spoils",desc:"When you KO an enemy ghost: gain 1 Sacred Fire, 2 Ice Shards, 1 Lucky Stone, 1 Moonstone, 2 Healing Seeds.",set:"Dark Castle",art:"../testroom/art/originals/ValkinTheGrand.png"},
  {id:433,name:"Lucas",rarity:"uncommon",maxHp:5,ability:"Kindling",desc:"Sideline: When a ghost is revived, it charges into play with +3 HP and +1 die next roll. The reviver steps to the sideline.",set:"Volcanic Isles",art:"../testroom/art/originals/Vigil.png"},
  {id:435,name:"Willow",rarity:"ghost-rare",maxHp:4,ability:"Joy of Painting",desc:"Sideline & In Play: gain +1 die if you lost the last roll.",set:"Dark Castle",art:"../testroom/art/originals/Willow.png"},
  {id:436,name:"Princess Shade",rarity:"rare",maxHp:4,ability:"Bounty",desc:"While in play & on sideline: when the enemy ghost takes damage before the roll, deal +1 additional damage.",set:"Dark Castle",art:"../testroom/art/originals/PrincessShade.png"},
  {id:437,name:"Rascals",rarity:"common",maxHp:3,ability:"Stampede",desc:"Entry: gain 3 Burn.",set:"Dark Castle",art:"../testroom/art/originals/Rascals.png"},
  {id:438,name:"Champ",rarity:"ghost rare",maxHp:5,ability:"Thrill",desc:"Immune to damage from Specials. Gains +1 Surge when you or the enemy rolls doubles or higher.",set:"Dark Castle",art:"../testroom/art/originals/Champ.png"},
  {id:439,name:"Lucy\'s Shadow",rarity:"rare",maxHp:4,ability:"Mentor",desc:"Sideline: while Lucy is in play, Lucy gains +1 extra Sacred Fire on wins and her Sacred Fires deal double damage.",set:"Dark Castle",art:"../testroom/art/originals/LucysShadow.png"},
  {id:440,name:"Gom Gom Gom",rarity:"common",maxHp:5,ability:"Chaos",desc:"Win with doubles: gain 1 Sacred Fire.",set:"Dark Castle",art:"../testroom/art/originals/DCFlameball.png"},
  {id:441,name:"Wendy",rarity:"rare",maxHp:3,ability:"Moonbeam",desc:"Win with doubles or better: gain 1 Magic Firefly.",set:"Dark Castle",art:"../testroom/art/originals/DCMoonDragon.png"},
  {id:442,name:"Castle Gardener",rarity:"common",maxHp:2,ability:"Cultivate",desc:"Before rolling: you may discard Healing Seeds to gain 2 Sacred Fire each.",set:"Dark Castle",art:"../testroom/art/originals/Gardener.png"},
  {id:443,name:"Captain James",rarity:"rare",maxHp:6,ability:"Final Strike",desc:"Roll: if you roll triples or higher, gain 2 Sacred Fires.",set:"Dark Castle",art:"../testroom/art/originals/DCKnight.png"},
  {id:444,name:"Goobs",rarity:"common",maxHp:4,ability:"Dance Party",desc:"Sideline & In Play: on a tie, both players gain 1 Magic Firefly. +5 HP to your current Ghost in Play.",set:"Rolling Hills",art:"../testroom/art/originals/GoobParty.png"},
  {id:445,name:"Michael",rarity:"uncommon",maxHp:5,ability:"Torrent",desc:"Even doubles: deal +2 damage. While in play, your sideline ghosts are immune to Burn.",set:"Volcanic Isles",art:"../testroom/art/originals/WaterSpirit.png"},
  {id:446,name:"Mable Stadango",rarity:"rare",maxHp:5,ability:"Hex",desc:"Before rolling: you may spend 1 Burn to remove 1 enemy die this roll and gain 1 Sacred Fire.",set:"Rolling Hills",art:"../testroom/art/originals/ForestSpirit.png"},
  {id:447,name:"Professor Hawking",rarity:"rare",maxHp:2,ability:"Wisdom",desc:"While in play: gain +2 dice if you are holding a Moonstone.",set:"Rolling Hills",art:"../testroom/art/originals/ProfessorHawking.png"},
  {id:448,name:"Harvey",rarity:"uncommon",maxHp:6,ability:"Harvest Moon",desc:"Win: if you rolled any fives, gain 1 Moonstone. (Max 1 Moonstone)",set:"Dark Castle",art:"../testroom/art/originals/TreeMonster.png"},
  {id:449,name:"Carpenter",rarity:"common",maxHp:4,ability:"Crafty",desc:"Win: +2 damage on singles. If you use a Surge, transform into Welder. Gain the Hammer.",set:"Volcanic Isles",art:"../testroom/art/originals/Carpenter.png"},
  {id:450,name:"Welder",rarity:"rare",maxHp:5,ability:"Flux",desc:"Win: gain 1 Burn. Roll a 4: transform into Foreman. Gain the Torch.",set:"Volcanic Isles",art:"../testroom/art/originals/Welder.png"},
  {id:451,name:"Foreman",rarity:"rare",maxHp:5,ability:"Blueprint",desc:"Win: +1 die next roll.",set:"Volcanic Isles",art:"../testroom/art/originals/Foreman.png"},
  {id:452,name:"Ripagoo",rarity:"uncommon",maxHp:5,ability:"Chemical Y",desc:"Sideline: if a card in play transforms, gain 2 Burn.",set:"Volcanic Isles",art:"../testroom/art/originals/Ripagoo.png"},
  {id:453,name:"Kaylee",rarity:"ghost-rare",maxHp:6,ability:"Slipstream",desc:"If any of your dice shows a 2: you may swap one of your dice with one of your opponent\'s dice.",set:"Rolling Hills",art:"../testroom/art/originals/Kaylee.jpeg"},
  {id:454,name:"Miyoshi",rarity:"ghost-rare",maxHp:6,ability:"Bonzai!",desc:"Before rolling: you may declare \'Bonzai!\' — lose 4 HP first, then gain +5 dice.",set:"Volcanic Isles",art:"../testroom/art/originals/Miyoshi.jpeg"},
  {id:455,name:"Explorer Jeff",rarity:"rare",maxHp:4,ability:"Treasure Hunter",desc:"While on the sideline or in play: if you hold 3+ different specials, gain +1 die and +1 damage.",set:"Volcanic Isles",art:"../testroom/art/originals/ExplorerJeff.png"},
  {id:456,name:"Ryder",rarity:"rare",maxHp:5,ability:"Toll",desc:"Before rolling: opponent chooses — take 1 damage or give Ryder +1 Sacred Fire.",set:"Dark Castle",art:"../testroom/art/originals/Ryder.png"},
  {id:457,name:"Sophia",rarity:"rare",maxHp:6,ability:"Masquerade",desc:"On Win: you may deal no damage. If you do, gain Mask of Day or Mask of Night (once per game).",set:"Dark Castle",art:"../testroom/art/originals/Sophia.png"},
  {id:458,name:"Maisie",rarity:"ghost-rare",maxHp:4,ability:"Lucky",desc:"All your 1s count as 5s.",set:"Rolling Hills",art:"../testroom/art/originals/Maisie.png"},
  {id:459,name:"Eli",rarity:"common",maxHp:4,ability:"Steady",desc:"Before rolling: gain +1 Lucky Stone.",set:"Rolling Hills",art:"../testroom/art/originals/Eli.png"},
  {id:460,name:"Slicer",rarity:"uncommon",maxHp:6,ability:"Parting Gift",desc:"Sideline & In Play: if you win with Quads or better, destroy an enemy sideline Spiritkin.",set:"Dark Castle",art:"../testroom/art/slicer.png"},
  {id:461,name:"Ronan",rarity:"common",maxHp:5,ability:"Mixup",desc:"If you roll doubles, gain +1 Ice Shard & +1 Burn.",set:"Volcanic Isles",art:"../testroom/art/ronan.png"},
  {id:462,name:"Ridley",rarity:"uncommon",maxHp:3,ability:"Nimble",desc:"Singles deal +1 damage. Doubles deal +2 damage.",set:"Rolling Hills",art:"../testroom/art/ridley.png"},
  {id:463,name:"Zork",rarity:"common",maxHp:4,ability:"Smolder",desc:"Before rolling: discard Burn to gain +1 die per Burn discarded.",set:"Volcanic Isles",art:"../testroom/art/zork.png"},
  {id:464,name:"Yawn Eater",rarity:"uncommon",maxHp:7,ability:"Feast",desc:"Gain +1 die for each sideline ability on the enemy sideline. Odd doubles deal +1 damage.",set:"Dark Castle",art:"../testroom/art/originals/YawnEater.png"}
];

// Legacy — used for internal reference, not player-selectable
const DISCIPLINES = [
  { id: 'hunter', name: 'Hunter', icon: '&#127993;', desc: 'Combat bonuses, better wild encounter rates', color: '#c44' },
  { id: 'artificer', name: 'Artificer', icon: '&#128295;', desc: 'Crafting bonuses, extra experimentation', color: '#4ac' },
  { id: 'merchant', name: 'Merchant', icon: '&#128142;', desc: 'Better trades, larger shop inventory', color: '#ca4' },
  { id: 'scout', name: 'Scout', icon: '&#128506;&#65039;', desc: 'Finds rarer resources, reveals hidden zones', color: '#4a4' },
];
