#!/usr/bin/env node
// Build /play/cards/{id}.webp + /play/js/data.js from the canonical roster.
// Sources:
//   ~/DrBango/carddashboard2/index.html  -> `let spirits = [...]` (lore/appearance/collection order)
//                                        -> `const CARD_IMAGES = {name: filename}` (art map)
//   ../engine/cards.js                   -> GHOSTS + SHELVED_IDS (engine truth: ids, stats, text)
// Usage: node build-art.mjs [--skip-images]
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import { homedir } from 'os';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const HERE = dirname(fileURLToPath(import.meta.url));
const DASH = join(homedir(), 'DrBango/carddashboard2');
const OUT_CARDS = join(HERE, '..', 'cards');
const OUT_DATA = join(HERE, '..', 'js', 'data.js');
const SKIP_IMAGES = process.argv.includes('--skip-images');

function extractBlock(src, startMarker, open, close) {
  const i = src.indexOf(startMarker);
  if (i < 0) throw new Error('marker not found: ' + startMarker);
  const j = src.indexOf(open, i);
  let depth = 0, k = j;
  for (; k < src.length; k++) {
    if (src[k] === open) depth++;
    else if (src[k] === close) { depth--; if (depth === 0) break; }
  }
  return src.slice(j, k + 1);
}

const dashHtml = readFileSync(join(DASH, 'index.html'), 'utf8');
const spirits = eval(extractBlock(dashHtml, 'let spirits = [', '[', ']'));
const cardImages = eval('(' + extractBlock(dashHtml, 'const CARD_IMAGES', '{', '}') + ')');

const cardsJs = readFileSync(join(HERE, '..', 'engine', 'cards.js'), 'utf8');
const sandbox = {};
new Function(cardsJs + '\nreturn {GHOSTS, SHELVED_IDS};').call(sandbox); // just to fail fast on syntax
const engine = new Function(cardsJs + '\nreturn {GHOSTS, SHELVED_IDS};')();
const active = engine.GHOSTS.filter(g => !engine.SHELVED_IDS.has(g.id));

// --- sanity: engine active set == dashboard set, by id AND name ---
const byIdA = new Map(spirits.map(s => [s.id, s]));
const problems = [];
if (active.length !== spirits.length) problems.push(`count mismatch engine=${active.length} dash=${spirits.length}`);
for (const g of active) {
  const a = byIdA.get(g.id);
  if (!a) { problems.push(`engine id ${g.id} (${g.name}) missing from dashboard`); continue; }
  if (a.name.trim().toLowerCase() !== g.name.trim().toLowerCase())
    problems.push(`id ${g.id}: name mismatch engine="${g.name}" dash="${a.name}"`);
}
if (problems.length) { console.error('RECONCILIATION PROBLEMS:\n' + problems.join('\n')); process.exit(1); }

// --- collection numbers = dashboard array order (load-bearing there) ---
const numById = new Map(spirits.map((s, i) => [s.id, i + 1]));

// --- images ---
mkdirSync(OUT_CARDS, { recursive: true });
let converted = 0, missing = [];
if (!SKIP_IMAGES) {
  for (const s of spirits) {
    const file = cardImages[s.name];
    const src = file && join(DASH, 'cards', file);
    if (!src || !existsSync(src)) { missing.push(`${s.id} ${s.name} -> ${file || 'NO MAP ENTRY'}`); continue; }
    const out = join(OUT_CARDS, `${s.id}.webp`);
    execSync(`magick ${JSON.stringify(src)} -auto-orient -resize '900x900>' -quality 82 ${JSON.stringify(out)}`);
    converted++;
  }
}

// --- data.js overlay (presentation-only; engine/cards.js stays the gameplay truth) ---
const meta = {};
for (const s of spirits) {
  const m = { num: numById.get(s.id) };
  if (s.lore) m.lore = s.lore;
  if (s.appearance) m.appearance = s.appearance;
  meta[s.id] = m;
}
const SETS = [
  { key: 'Set 1',          short: 'SET 1',          color: '#d4a040' },
  { key: 'Frost Valley',   short: 'FROST VALLEY',   color: '#7dd3fc' },
  { key: 'Rolling Hills',  short: 'ROLLING HILLS',  color: '#86efac' },
  { key: 'Dark Castle',    short: 'DARK CASTLE',    color: '#c084fc' },
  { key: 'Volcanic Isles', short: 'VOLCANIC ISLES', color: '#fb923c' },
];
const banner = `// GENERATED by tools/build-art.mjs — do not hand-edit the META block.
// Presentation overlay for the 200 active Spiritkin. Gameplay truth = engine/cards.js.
// Art: cards/{id}.webp (optimized from ~/DrBango/carddashboard2/cards/, ${converted} files).
// NOTE 14 cards have newer text in carddashboard2 than the engine executes (engine text
// is shown in-game; flagged for Wyatt): Knight Terror(HP 7vs6), Champ(rarity typo),
// City Cyboo, Cameron, Piper (ability name+desc), Twyla, Valkin the Grand, Splinter,
// Laura, Zach (desc), Fredrick, Pelter, Calvin & Anna (category).`;
const dataJs = `${banner}
window.BOO2_SETS = ${JSON.stringify(SETS, null, 2)};
window.BOO2_META = ${JSON.stringify(meta)};
window.boo2Art = id => 'cards/' + id + '.webp';
window.boo2Num = id => (BOO2_META[id] || {}).num || 0;
`;
mkdirSync(dirname(OUT_DATA), { recursive: true });
writeFileSync(OUT_DATA, dataJs);
console.log(`OK: ${spirits.length} spirits, ${converted} images converted, data.js written.`);
if (missing.length) console.log('MISSING ART:\n' + missing.join('\n'));
